// <auto-generated />
namespace d5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class baza2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(baza2));
        
        string IMigrationMetadata.Id
        {
            get { return "201805142310555_baza2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
